#include <stdio.h>
#include <openssl/bn.h>

int main() {
    BN_CTX *ctx = BN_CTX_new();

    BIGNUM *p = BN_new();
    BIGNUM *g = BN_new();
    BIGNUM *xa = BN_new();  // Alice's ephemeral message key
    BIGNUM *xb = BN_new();  // Bob's secret key
    BIGNUM *yb = BN_new();  // Bob's public key
    BIGNUM *K = BN_new();   // Shared secret
    BIGNUM *C1 = BN_new();
    BIGNUM *C2 = BN_new();
    BIGNUM *M = BN_new();
    BIGNUM *temp = BN_new();

    // Set values
    BN_dec2bn(&p, "773");
    BN_dec2bn(&g, "200");
    BN_dec2bn(&xa, "333");  // Ephemeral key generated by Alice (sender)
    BN_dec2bn(&xb, "603");  // Bob's private key (receiver)
    BN_dec2bn(&M, "321");

    // Compute Bob's public key: y_b = g^x_b mod p
    BN_mod_exp(yb, g, xb, p, ctx);

    // C1 = g^x_a mod p
    BN_mod_exp(C1, g, xa, p, ctx);

    // K = y_b^x_a mod p
    BN_mod_exp(K, yb, xa, p, ctx);

    // C2 = (M * K) mod p
    BN_mul(temp, M, K, ctx);
    BN_mod(C2, temp, p, ctx);

    // Output
    char *yb_str = BN_bn2dec(yb);
    char *C1_str = BN_bn2dec(C1);
    char *C2_str = BN_bn2dec(C2);
    char *K_str = BN_bn2dec(K);

    printf("Bob's public key (y_b): %s\n", yb_str);
    printf("Ephemeral key (x_a): 333\n");
    printf("Ephemeral message key (K): %s\n", K_str);
    printf("Ciphertext (C1, C2): (%s, %s)\n", C1_str, C2_str);

    // Cleanup
    OPENSSL_free(yb_str);
    OPENSSL_free(C1_str);
    OPENSSL_free(C2_str);
    OPENSSL_free(K_str);
    BN_free(p); BN_free(g); BN_free(xa); BN_free(xb);
    BN_free(yb); BN_free(K); BN_free(C1); BN_free(C2); BN_free(M); BN_free(temp);
    BN_CTX_free(ctx);

    return 0;
}
